version: "3.9"

services:
  filewatcher:
    image: filewatcher-java
    container_name: filewatcher-java
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      FW_WATCH_DIRS_0: "/app/dir"
      FW_WATCH_DIRS_1: "/app/dir/sub"
    volumes:
      - ./dir:/app/dir